#############################################################################
# Makefile for building: xpcsMPI
# Generated by qmake (2.01a) (Qt 4.8.4) on: Thu Mar 26 15:34:34 2015
# Project:  xpcsMPI.pro
# Template: app
# Command: /home/oxygen26/TMADDEN/QTStuff/qt4.8/bin/qmake -o Makefile xpcsMPI.pro
#############################################################################

####### Compiler, tools and options

CC            = mpicc
CXX           = mpic++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -DMPICH_IGNORE_CXX_SEEK -DUSE_MPI -O2 -DMPICH_IGNORE_CXX_SEEK -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QTStuff/qt4.8/mkspecs/default -I. -I../../QTStuff/qt4.8/include/QtCore -I../../QTStuff/qt4.8/include/QtNetwork -I../../QTStuff/qt4.8/include/QtGui -I../../QTStuff/qt4.8/include -ICommon -IXPCS -I. -I.
LINK          = mpic++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib
LIBS          = $(SUBLIBS)  -L/home/oxygen26/TMADDEN/QTStuff/qt4.8//lib -lQtGui -L/home/oxygen26/TMADDEN/QTStuff/qt4.8//lib -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/oxygen26/TMADDEN/QTStuff/qt4.8/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Common/mpicalcrunner.cpp \
		Common/mpimesgrecvr.cpp \
		Common/mpiengine.cpp \
		XPCS/imagequeueitem.cpp \
		Common/mpiScatter.cpp \
		Common/mpiGather.cpp \
		Common/pipeReader.cpp \
		Common/pipewriter.cpp \
		Common/tinytiff.cpp \
		Common/pipebinaryformat.cpp \
		Common/imageStreamTest.cpp \
		XPCS/imm.cpp \
		Common/signalmessage.cpp \
		XPCS/mpiUser.cpp \
		XPCS/mpigatherUser.cpp \
		XPCS/mpiscatterUser.cpp \
		XPCS/mpicontrolgui.cpp \
		XPCS/signalmessageUser.cpp \
		XPCS/main_mpi.cpp moc_mpicalcrunner.cpp \
		moc_mpimesgrecvr.cpp \
		moc_mpiengine.cpp \
		moc_imagequeueitem.cpp \
		moc_mpiScatter.cpp \
		moc_mpiGather.cpp \
		moc_pipeReader.cpp \
		moc_pipewriter.cpp \
		moc_mpicontrolgui.cpp
OBJECTS       = mpicalcrunner.o \
		mpimesgrecvr.o \
		mpiengine.o \
		imagequeueitem.o \
		mpiScatter.o \
		mpiGather.o \
		pipeReader.o \
		pipewriter.o \
		tinytiff.o \
		pipebinaryformat.o \
		imageStreamTest.o \
		imm.o \
		signalmessage.o \
		mpiUser.o \
		mpigatherUser.o \
		mpiscatterUser.o \
		mpicontrolgui.o \
		signalmessageUser.o \
		main_mpi.o \
		moc_mpicalcrunner.o \
		moc_mpimesgrecvr.o \
		moc_mpiengine.o \
		moc_imagequeueitem.o \
		moc_mpiScatter.o \
		moc_mpiGather.o \
		moc_pipeReader.o \
		moc_pipewriter.o \
		moc_mpicontrolgui.o
DIST          = ../../QTStuff/qt4.8/mkspecs/common/unix.conf \
		../../QTStuff/qt4.8/mkspecs/common/linux.conf \
		../../QTStuff/qt4.8/mkspecs/common/gcc-base.conf \
		../../QTStuff/qt4.8/mkspecs/common/gcc-base-unix.conf \
		../../QTStuff/qt4.8/mkspecs/common/g++-base.conf \
		../../QTStuff/qt4.8/mkspecs/common/g++-unix.conf \
		../../QTStuff/qt4.8/mkspecs/qconfig.pri \
		../../QTStuff/qt4.8/mkspecs/features/qt_functions.prf \
		../../QTStuff/qt4.8/mkspecs/features/qt_config.prf \
		../../QTStuff/qt4.8/mkspecs/features/exclusive_builds.prf \
		../../QTStuff/qt4.8/mkspecs/features/default_pre.prf \
		../../QTStuff/qt4.8/mkspecs/features/release.prf \
		../../QTStuff/qt4.8/mkspecs/features/default_post.prf \
		../../QTStuff/qt4.8/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../QTStuff/qt4.8/mkspecs/features/warn_on.prf \
		../../QTStuff/qt4.8/mkspecs/features/qt.prf \
		../../QTStuff/qt4.8/mkspecs/features/unix/thread.prf \
		../../QTStuff/qt4.8/mkspecs/features/moc.prf \
		../../QTStuff/qt4.8/mkspecs/features/resources.prf \
		../../QTStuff/qt4.8/mkspecs/features/uic.prf \
		../../QTStuff/qt4.8/mkspecs/features/yacc.prf \
		../../QTStuff/qt4.8/mkspecs/features/lex.prf \
		../../QTStuff/qt4.8/mkspecs/features/include_source_dir.prf \
		xpcsMPI.pro
QMAKE_TARGET  = xpcsMPI
DESTDIR       = 
TARGET        = xpcsMPI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mpicontrolgui.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: xpcsMPI.pro  ../../QTStuff/qt4.8/mkspecs/default/qmake.conf ../../QTStuff/qt4.8/mkspecs/common/unix.conf \
		../../QTStuff/qt4.8/mkspecs/common/linux.conf \
		../../QTStuff/qt4.8/mkspecs/common/gcc-base.conf \
		../../QTStuff/qt4.8/mkspecs/common/gcc-base-unix.conf \
		../../QTStuff/qt4.8/mkspecs/common/g++-base.conf \
		../../QTStuff/qt4.8/mkspecs/common/g++-unix.conf \
		../../QTStuff/qt4.8/mkspecs/qconfig.pri \
		../../QTStuff/qt4.8/mkspecs/features/qt_functions.prf \
		../../QTStuff/qt4.8/mkspecs/features/qt_config.prf \
		../../QTStuff/qt4.8/mkspecs/features/exclusive_builds.prf \
		../../QTStuff/qt4.8/mkspecs/features/default_pre.prf \
		../../QTStuff/qt4.8/mkspecs/features/release.prf \
		../../QTStuff/qt4.8/mkspecs/features/default_post.prf \
		../../QTStuff/qt4.8/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../QTStuff/qt4.8/mkspecs/features/warn_on.prf \
		../../QTStuff/qt4.8/mkspecs/features/qt.prf \
		../../QTStuff/qt4.8/mkspecs/features/unix/thread.prf \
		../../QTStuff/qt4.8/mkspecs/features/moc.prf \
		../../QTStuff/qt4.8/mkspecs/features/resources.prf \
		../../QTStuff/qt4.8/mkspecs/features/uic.prf \
		../../QTStuff/qt4.8/mkspecs/features/yacc.prf \
		../../QTStuff/qt4.8/mkspecs/features/lex.prf \
		../../QTStuff/qt4.8/mkspecs/features/include_source_dir.prf \
		/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib/libQtGui.prl \
		/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib/libQtCore.prl \
		/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile xpcsMPI.pro
../../QTStuff/qt4.8/mkspecs/common/unix.conf:
../../QTStuff/qt4.8/mkspecs/common/linux.conf:
../../QTStuff/qt4.8/mkspecs/common/gcc-base.conf:
../../QTStuff/qt4.8/mkspecs/common/gcc-base-unix.conf:
../../QTStuff/qt4.8/mkspecs/common/g++-base.conf:
../../QTStuff/qt4.8/mkspecs/common/g++-unix.conf:
../../QTStuff/qt4.8/mkspecs/qconfig.pri:
../../QTStuff/qt4.8/mkspecs/features/qt_functions.prf:
../../QTStuff/qt4.8/mkspecs/features/qt_config.prf:
../../QTStuff/qt4.8/mkspecs/features/exclusive_builds.prf:
../../QTStuff/qt4.8/mkspecs/features/default_pre.prf:
../../QTStuff/qt4.8/mkspecs/features/release.prf:
../../QTStuff/qt4.8/mkspecs/features/default_post.prf:
../../QTStuff/qt4.8/mkspecs/features/unix/gdb_dwarf_index.prf:
../../QTStuff/qt4.8/mkspecs/features/warn_on.prf:
../../QTStuff/qt4.8/mkspecs/features/qt.prf:
../../QTStuff/qt4.8/mkspecs/features/unix/thread.prf:
../../QTStuff/qt4.8/mkspecs/features/moc.prf:
../../QTStuff/qt4.8/mkspecs/features/resources.prf:
../../QTStuff/qt4.8/mkspecs/features/uic.prf:
../../QTStuff/qt4.8/mkspecs/features/yacc.prf:
../../QTStuff/qt4.8/mkspecs/features/lex.prf:
../../QTStuff/qt4.8/mkspecs/features/include_source_dir.prf:
/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib/libQtGui.prl:
/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib/libQtCore.prl:
/home/oxygen26/TMADDEN/QTStuff/qt4.8/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile xpcsMPI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/xpcsMPI1.0.0 || $(MKDIR) .tmp/xpcsMPI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/xpcsMPI1.0.0/ && $(COPY_FILE) --parents Common/mpicalcrunner.h Common/mpimesgrecvr.h Common/mpiengine.h XPCS/imagequeueitem.h Common/mpiScatter.h Common/mpiGather.h Common/pipeReader.h Common/pipewriter.h Common/tinytiff.h Common/pipebinaryformat.h XPCS/imm.h XPCS/imm_header.h Common/signalmessage.h XPCS/signalmessageUser.h XPCS/mpiUser.h XPCS/mpigatherUser.h XPCS/mpicontrolgui.h XPCS/mpiscatterUser.h .tmp/xpcsMPI1.0.0/ && $(COPY_FILE) --parents Common/mpicalcrunner.cpp Common/mpimesgrecvr.cpp Common/mpiengine.cpp XPCS/imagequeueitem.cpp Common/mpiScatter.cpp Common/mpiGather.cpp Common/pipeReader.cpp Common/pipewriter.cpp Common/tinytiff.cpp Common/pipebinaryformat.cpp Common/imageStreamTest.cpp XPCS/imm.cpp Common/signalmessage.cpp XPCS/mpiUser.cpp XPCS/mpigatherUser.cpp XPCS/mpiscatterUser.cpp XPCS/mpicontrolgui.cpp XPCS/signalmessageUser.cpp XPCS/main_mpi.cpp .tmp/xpcsMPI1.0.0/ && $(COPY_FILE) --parents XPCS/mpicontrolgui.ui .tmp/xpcsMPI1.0.0/ && (cd `dirname .tmp/xpcsMPI1.0.0` && $(TAR) xpcsMPI1.0.0.tar xpcsMPI1.0.0 && $(COMPRESS) xpcsMPI1.0.0.tar) && $(MOVE) `dirname .tmp/xpcsMPI1.0.0`/xpcsMPI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/xpcsMPI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mpicalcrunner.cpp moc_mpimesgrecvr.cpp moc_mpiengine.cpp moc_imagequeueitem.cpp moc_mpiScatter.cpp moc_mpiGather.cpp moc_pipeReader.cpp moc_pipewriter.cpp moc_mpicontrolgui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mpicalcrunner.cpp moc_mpimesgrecvr.cpp moc_mpiengine.cpp moc_imagequeueitem.cpp moc_mpiScatter.cpp moc_mpiGather.cpp moc_pipeReader.cpp moc_pipewriter.cpp moc_mpicontrolgui.cpp
moc_mpicalcrunner.cpp: Common/mpiengine.h \
		Common/signalmessage.h \
		Common/mpicalcrunner.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/mpicalcrunner.h -o moc_mpicalcrunner.cpp

moc_mpimesgrecvr.cpp: Common/mpicalcrunner.h \
		Common/mpiengine.h \
		Common/signalmessage.h \
		Common/mpimesgrecvr.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/mpimesgrecvr.h -o moc_mpimesgrecvr.cpp

moc_mpiengine.cpp: Common/signalmessage.h \
		Common/mpiengine.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/mpiengine.h -o moc_mpiengine.cpp

moc_imagequeueitem.cpp: XPCS/imagequeueitem.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) XPCS/imagequeueitem.h -o moc_imagequeueitem.cpp

moc_mpiScatter.cpp: Common/mpiengine.h \
		Common/signalmessage.h \
		Common/mpiScatter.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/mpiScatter.h -o moc_mpiScatter.cpp

moc_mpiGather.cpp: Common/pipeReader.h \
		Common/pipebinaryformat.h \
		Common/signalmessage.h \
		Common/mpiengine.h \
		Common/mpiGather.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/mpiGather.h -o moc_mpiGather.cpp

moc_pipeReader.cpp: Common/pipebinaryformat.h \
		Common/signalmessage.h \
		Common/pipeReader.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/pipeReader.h -o moc_pipeReader.cpp

moc_pipewriter.cpp: Common/signalmessage.h \
		Common/tinytiff.h \
		Common/pipebinaryformat.h \
		Common/pipewriter.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) Common/pipewriter.h -o moc_pipewriter.cpp

moc_mpicontrolgui.cpp: XPCS/imagequeueitem.h \
		XPCS/mpicontrolgui.h
	/home/oxygen26/TMADDEN/QTStuff/qt4.8//bin/moc $(DEFINES) $(INCPATH) XPCS/mpicontrolgui.h -o moc_mpicontrolgui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mpicontrolgui.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mpicontrolgui.h
ui_mpicontrolgui.h: XPCS/mpicontrolgui.ui
	/home/oxygen26/TMADDEN/QTStuff/qt4.8/bin/uic XPCS/mpicontrolgui.ui -o ui_mpicontrolgui.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

mpicalcrunner.o: Common/mpicalcrunner.cpp Common/mpicalcrunner.h \
		Common/mpiengine.h \
		Common/signalmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpicalcrunner.o Common/mpicalcrunner.cpp

mpimesgrecvr.o: Common/mpimesgrecvr.cpp Common/mpimesgrecvr.h \
		Common/mpicalcrunner.h \
		Common/mpiengine.h \
		Common/signalmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpimesgrecvr.o Common/mpimesgrecvr.cpp

mpiengine.o: Common/mpiengine.cpp Common/mpiengine.h \
		Common/signalmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpiengine.o Common/mpiengine.cpp

imagequeueitem.o: XPCS/imagequeueitem.cpp XPCS/imagequeueitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagequeueitem.o XPCS/imagequeueitem.cpp

mpiScatter.o: Common/mpiScatter.cpp Common/mpiScatter.h \
		Common/mpiengine.h \
		Common/signalmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpiScatter.o Common/mpiScatter.cpp

mpiGather.o: Common/mpiGather.cpp Common/mpiGather.h \
		Common/pipeReader.h \
		Common/pipebinaryformat.h \
		Common/signalmessage.h \
		Common/mpiengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpiGather.o Common/mpiGather.cpp

pipeReader.o: Common/pipeReader.cpp Common/pipeReader.h \
		Common/pipebinaryformat.h \
		Common/signalmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipeReader.o Common/pipeReader.cpp

pipewriter.o: Common/pipewriter.cpp Common/pipewriter.h \
		Common/signalmessage.h \
		Common/tinytiff.h \
		Common/pipebinaryformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipewriter.o Common/pipewriter.cpp

tinytiff.o: Common/tinytiff.cpp Common/tinytiff.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinytiff.o Common/tinytiff.cpp

pipebinaryformat.o: Common/pipebinaryformat.cpp Common/pipebinaryformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipebinaryformat.o Common/pipebinaryformat.cpp

imageStreamTest.o: Common/imageStreamTest.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageStreamTest.o Common/imageStreamTest.cpp

imm.o: XPCS/imm.cpp XPCS/imm.h \
		XPCS/imm_header.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imm.o XPCS/imm.cpp

signalmessage.o: Common/signalmessage.cpp Common/signalmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalmessage.o Common/signalmessage.cpp

mpiUser.o: XPCS/mpiUser.cpp XPCS/mpiUser.h \
		XPCS/imm.h \
		XPCS/imm_header.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpiUser.o XPCS/mpiUser.cpp

mpigatherUser.o: XPCS/mpigatherUser.cpp XPCS/mpigatherUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpigatherUser.o XPCS/mpigatherUser.cpp

mpiscatterUser.o: XPCS/mpiscatterUser.cpp XPCS/mpiscatterUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpiscatterUser.o XPCS/mpiscatterUser.cpp

mpicontrolgui.o: XPCS/mpicontrolgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpicontrolgui.o XPCS/mpicontrolgui.cpp

signalmessageUser.o: XPCS/signalmessageUser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalmessageUser.o XPCS/signalmessageUser.cpp

main_mpi.o: XPCS/main_mpi.cpp XPCS/mpicontrolgui.h \
		XPCS/imagequeueitem.h \
		XPCS/mpiUser.h \
		XPCS/imm.h \
		XPCS/imm_header.h \
		XPCS/mpiscatterUser.h \
		XPCS/mpigatherUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_mpi.o XPCS/main_mpi.cpp

moc_mpicalcrunner.o: moc_mpicalcrunner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpicalcrunner.o moc_mpicalcrunner.cpp

moc_mpimesgrecvr.o: moc_mpimesgrecvr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpimesgrecvr.o moc_mpimesgrecvr.cpp

moc_mpiengine.o: moc_mpiengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpiengine.o moc_mpiengine.cpp

moc_imagequeueitem.o: moc_imagequeueitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagequeueitem.o moc_imagequeueitem.cpp

moc_mpiScatter.o: moc_mpiScatter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpiScatter.o moc_mpiScatter.cpp

moc_mpiGather.o: moc_mpiGather.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpiGather.o moc_mpiGather.cpp

moc_pipeReader.o: moc_pipeReader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pipeReader.o moc_pipeReader.cpp

moc_pipewriter.o: moc_pipewriter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pipewriter.o moc_pipewriter.cpp

moc_mpicontrolgui.o: moc_mpicontrolgui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpicontrolgui.o moc_mpicontrolgui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

